package digest

var maxLimit int64 = 50

var (
	defaultColNameAccount                     = "digest_ac"
	defaultColNameContractAccount             = "digest_ca"
	defaultColNameBalance                     = "digest_bl"
	defaultColNameCurrency                    = "digest_cr"
	defaultColNameOperation                   = "digest_op"
	defaultColNameBlock                       = "digest_bm"
	defaultColNameNFTCollection               = "digest_nftcollection"
	defaultColNameNFT                         = "digest_nft"
	defaultColNameNFTOperator                 = "digest_nftoperator"
	defaultColNameDIDCredentialService        = "digest_did_issuer"
	defaultColNameDIDCredential               = "digest_did_credential"
	defaultColNameHolder                      = "digest_did_holder_did"
	defaultColNameTemplate                    = "digest_did_template"
	defaultColNameTimeStamp                   = "digest_ts"
	defaultColNameToken                       = "digest_token"
	defaultColNameTokenBalance                = "digest_token_bl"
	defaultColNamePoint                       = "digest_point"
	defaultColNamePointBalance                = "digest_point_bl"
	defaultColNameDAO                         = "digest_dao_de"
	defaultColNameDAOProposal                 = "digest_dao_pr"
	defaultColNameDAODelegators               = "digest_dao_dac"
	defaultColNameDAOVoters                   = "digest_dao_vac"
	defaultColNameDAOVotingPowerBox           = "digest_dao_vpb"
	defaultColNameSTO                         = "digest_sto_de"
	defaultColNameSTOHolderPartitions         = "digest_sto_hac_pt"
	defaultColNameSTOHolderPartitionBalance   = "digest_sto_hac_pt_bl"
	defaultColNameSTOHolderPartitionOperators = "digest_sto_hac_pt_oac"
	defaultColNameSTOPartitionBalance         = "digest_sto_pt_bl"
	defaultColNameSTOPartitionControllers     = "digest_sto_pt_cac"
	defaultColNameSTOOperatorHolders          = "digest_sto_oac_hac"
)
